Implementacion del metodo actualizar  mascota
code3743/MiniProyecto1 pull request #29
Opened 2023-04-22 23:40 UTC by JAMM0118

El compañero Posso y yo realizamos la implementación del método actualizar mascota donde se modificaran los datos de la mascota ingresada  y se le asignaran sus vacunas

2023-04-23 16:33 UTC, code3743 requested changes

2023-04-23 17:10 UTC, JAMM0118 commented on src/controllers/VeterinariaController.java
> +        if(veterinaria.listarMascotas().size()!=0){
Listo, corrección hecha

2023-04-23 17:10 UTC, JAMM0118 commented on src/controllers/VeterinariaController.java
> +                    String nombreMascota = IOConsola.leerString("Ingrese el nombre de la mascota a actualizar: ").toLowerCase();
Corrección hecha

2023-04-24 11:54 UTC, code3743 requested changes

2023-04-24 11:54 UTC, code3743 commented on src/controllers/VeterinariaController.java
> +                    for( i=0 ; i< veterinaria.listarMascotas().size(); i++){
Aqui estoy haciendo la validacion dos veces del nombre, suguiero lo siguiente;
crear int indexMascota = -1; es importante inicializarlo con un numero que no este en el rango del arrayList de las mascotas, luego el fort tradicional con la validacion que tine:
for( int i=0 ; i< veterinaria.listarMascotas().size(); i++){
if (veterinaria.listarMascotas().get(i).getNombre().toLowerCase().equals(nombreMascota)){
                            indexMascota = i;
                            break;   
      }
}
luego en el if que esta abajo  if(veterinaria.buscarMascotaPorNombre(nombreMascota) != null) remplazarlo por
if(indexMascota != -1) y cada vez que llamen algun metodo de mascota para actualizar se debe llamar asi:
 veterinaria.listarMascotas().get(indexMascota).setNombre(newName) o puedes crear tambien una instancia de mascota con el metodo vecterinaria.elegirMascota(indexMascota) quedanado Mascota mascotaUpdate = vecterinaria.elegirMascota(indexMascota) y ya donde necesiten actulizar algo seria mascotaUpdate.setNombre(newName), y es importante que antes de salir de esa funcion si se aplica el metodo que digo hacer veterinaria.actualizarMascota(indexMascota, mascotaUpdate) ya queda a su discrecion que implementar.

2023-04-24 16:26 UTC, code3743 approved these changes
Bien alejo

2023-04-24 16:26 UTC, merged